services:
    server:
        build: ./API
        image: master-image
        ports: 
            - ${PORT:-5000}:5000
        command: gunicorn --workers 1 --bind 0.0.0.0:${PORT:-5000} --timeout 120 'server:create_app()'
        

    worker:
        image: master-image
        depends_on:
            - redis
        command: rq worker --name worker --url redis://redis:6379/0

    redis:
        image: redis